Dev
singleron-RD/CeleScope pull request #52
Opened 2021-08-30 07:35 UTC by Chenjunjie1996

realize preflight check for multi module

2021-08-30 09:42 UTC, zhouyiqi91 commented
1. add package version check
2. consider to use loops

2021-08-30 09:44 UTC, zhouyiqi91 requested changes
1. add package version check
2. consider using loops

2021-09-02 02:54 UTC, zhouyiqi91 requested changes

2021-09-02 02:54 UTC, zhouyiqi91 commented on celescope/tools/preflight.py
> +def run_prefligh(mapfile,outdir):
why not run_prefligh**t** ?

2021-09-02 02:54 UTC, zhouyiqi91 commented on celescope/tools/preflight.py
> +    PACKAGE_VERSION_CMDS = [
using loops and function

2021-09-02 03:05 UTC, zhouyiqi91 commented on celescope/tools/preflight.py
> +    print("Checking mapfile format and raw fastq file path...")
use celescope.tools.Multi.parse_mapfile

2021-09-02 07:16 UTC, Chenjunjie1996 commented on celescope/tools/preflight.py
> +def run_prefligh(mapfile,outdir):
Running preflight when calling multi module before celescope workflow.
can be tested in /SGRNJ03/randd/cjj/celedev/preflight_check/test
run shell in env: cjjdev

2022-03-07 09:58 UTC, closed without merging